#ifndef __SimpleBLEToolGUIFrame__
#define __SimpleBLEToolGUIFrame__

/**
@file
Subclass of GUIFrame, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

//// end generated include

/** Implementing GUIFrame */
class SimpleBLEToolGUIFrame : public GUIFrame
{
protected:
    // Handlers for GUIFrame events.
    void OnClose( wxCloseEvent& event );
    void OnAbout( wxCommandEvent& event );
public:
    /** Constructor */
    SimpleBLEToolGUIFrame( wxWindow* parent );
    //// end generated class members
    virtual ~SimpleBLEToolGUIFrame();

};

#endif // __SimpleBLEToolGUIFrame__
